name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: build
